#!/bin/sh

COMPRESSED=
TIME_REG='[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}'
ENTITY_REG="[^']*"
MON_REG='mon\.0'
LOG_LEVEL_REG='INF|DBG'
LONG_FORMAT=

description() {
    echo "process ceph.log"
}

help() {
    description
    echo
    echo "Commands: "
    echo "  cmd       - show commands only (default)"
    echo "  log       - show log file records"
    echo ""
    echo "Options:"
    echo "  -x          - process compressed logs too"
    echo "  -i          - show only info level commands"
    echo "  -l          - long format output"
    echo "  -e <entity> - show only for this entity"
    echo "  -m <mon.X>  - show entires logged by mon.X (default mon.0)"
}

log() {
    if [ -n "${COMPRESSED}" ]; then
      xzcat ${LOG_FILE}-*.xz
    fi
    cat ${LOG_FILE}
}

make_reg() {
    echo "$@" | sed -e 's/\./\\./g; s/\*/[a-zA-Z0-9_-]*/g'
}

cmd() {
    local extra=

    if [ -n "$LONG_FORMAT" ]; then
        extra='(\2) [\4] '
    fi

    log |
    sed -nEe '
      s/^('"${TIME_REG}"').*[ (]('"${MON_REG}"')[ )].* audit \[('"${LOG_LEVEL_REG}"')\] .* entity='"'(""${ENTITY_REG}"")'"' .*cmd=\[\{"prefix": (.*)\}\]: dispatch/\1 '"${extra}"'\5/p;
    ' |
    sed -e 's/"//g'
}

cmd=cmd

case "$1" in
    description)
        description
        exit 0
        ;;
    help)
        help
        exit 0
        ;;
    log)
        cmd=log
        shift
        ;;
esac

while getopts xile:m: name; do
    case $name in
        x)
            COMPRESSED=1
            ;;
        i)
            LOG_LEVEL_REG='INF'
            ;;
        l)
            LONG_FORMAT=1
            ;;
        e)
            ENTITY_REG="$(make_reg $OPTARG)"
            ;;
        m)
            MON_REG="$(make_reg $OPTARG)"
            ;;
        ?)
            echo "invalid option specified" >&2
            exit 1
        ;;
    esac
done

LOG_FILE="${SES_SUPPORTCONFIG_DIR}/ceph/log/ceph/ceph.audit.log"

if ! [ -e "${LOG_FILE}" ]; then
    echo "cannot find ${LOG_FILE}" >&2
    exit 1
fi

$cmd "$@"
