#!/bin/sh

description() {
    echo "process ceph.log"
}

help() {
    description
    echo
    echo "Commands: "
    echo "  show        - show log file records"
    echo "  pgmap [-p]  - show pgmap records"
}

show() {
    less $LOG_FILE
}

pgmap() {
    case "$1" in
        -p)
            # 2019-10-24 12:33:16.542142 mgr.tc3cmbE41216L client.874856120 172.23.192.1:0/538931070 6583636 : cluster [DBG] pgmap v4331819: 9248 pgs: 5 active+clean+scrubbing+deep, 9243 active+clean; 58.4TiB data, 174TiB used, 2.77PiB / 2.94PiB avail; 28.5MiB/s rd, 85.6MiB/s wr, 3.27kop/s
            grep ' pgmap v[0-9]*: ' $LOG_FILE |
            sed -nEe 's/^([0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]*) .*avail; (.*$)/\1 \2/p'
            ;;
        *)
            grep ' pgmap v[0-9]*: ' $LOG_FILE
            ;;
    esac
}

cmd=show

case "$1" in
    description)
        description
        exit 0
        ;;
    help)
        help
        exit 0
        ;;
    *)
        if [ "$#" -gt 0 ]; then
            cmd="$1"
            shift
        fi
        ;;
esac


LOG_FILE="${SES_SUPPORTCONFIG_DIR}/ceph/log/ceph/ceph.log"

if ! [ -e "${LOG_FILE}" ]; then
    echo "cannot find ${LOG_FILE}" >&2
    exit 1
fi

$cmd "$@"
