#!/usr/bin/env python3

import argparse
import json
import os
import re
import sys

#
# Global
#

SES_SUPPORTCONFIG_DIR = os.environ.get('SES_SUPPORTCONFIG_DIR')

cmd_description='print ceph daemon perf'

parser = argparse.ArgumentParser(prog='sesa perf', description=cmd_description)
parser.add_argument(
    '-d', '--daemon',
    metavar='mds.x|mon.x|osd.x',
    help='print ops for this daemon',
    default=None,
)
parser.add_argument(
    '-n', '--no-keys',
    action='store_true',
    help='print only values',
    default=False,
)
parser.add_argument(
    '-l', '--no-vals',
    action='store_true',
    help='print only keys',
    default=False,
)
parser.add_argument(
    'key',
    nargs='?',
    help='perf key (if not specified, list all keys)',
    default=None,
)
parser.add_argument(
    'subkey',
    help='perf sub-key',
    nargs='?',
    default=None,
)
parser.add_argument(
    'subsubkey',
    help='perf sub-sub-key',
    nargs='?',
    default=None,
)

#
# Functions
#

def description():
    print(cmd_description)

def help():
    parser.print_help()

def main():
    if len(sys.argv) > 1:
        if sys.argv[1] == 'description':
            description()
            exit(0)
        elif sys.argv[1] == 'help':
            help()
            exit(0)

    args = parser.parse_args()

    perf = {}
    for d in os.listdir(SES_SUPPORTCONFIG_DIR + '/ceph'):
        if args.daemon:
            if d != args.daemon:
                continue
        elif not re.match(r'^(mds|mon|osd)\.', d):
            continue
        f = open(SES_SUPPORTCONFIG_DIR + '/ceph/' + d +
                 '/ceph-daemon-perf', 'r')
        perf[d] = json.load(f)

    if not args.key:
        try:
            for d in sorted(perf.keys()):
                for key in sorted(perf[d].keys()):
                    print('%-8s %s' % (d, key))
                    sys.stdout.flush()
        except IOError as e:
            pass
        exit(0)

    #if args.sort_by_daemon:
    #    ops.sort(key=lambda op: op['daemon'])

    try:
        for d in sorted(perf.keys()):
            key = args.key
            if args.key not in perf[d]:
                continue
            val = perf[d][args.key]
            if args.subkey:
                key = key + ' ' + args.subkey
                if args.subkey not in val:
                    continue
                val = val[args.subkey]
            if args.subsubkey:
                key = key + ' ' + args.subsubkey
                if args.subsubkey not in val:
                    continue
                val = val[args.subsubkey]
            if args.no_vals:
                val = list(val)
            if args.no_keys:
                print('%-8s %s' % (d, val))
            else:
                print('%-8s %s %s' % (d, key, val))
            sys.stdout.flush()
    except IOError as e:
        pass

#
# main
#

main()
